name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  test:
    runs-on: ubuntu-latest
    container: clux/muslrust:stable
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build linux binary
      run: |
        mkdir -p out
        for PACK in anda_bot
        do
          export RUSTFLAGS="-C target-feature=+crt-static -C link-arg=-s"
          cargo build --release --locked -p $PACK --target x86_64-unknown-linux-musl
          cp "target/x86_64-unknown-linux-musl/release/$PACK" "out/"
          SHA256="$(sha256sum < "out/$PACK" | sed 's/ .*$//g')"
          echo $SHA256 > "out/$PACK.$SHA256.txt"
        done
        ls -lah out
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: out/*
